version: '3'

services:
  python-app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
    - ./redis-data:/data

volumes:
  redis-data:
    driver: local